version: "3"

services:
  fastapi:
    build: ./backend
    container_name: fastapi-container
    hostname: fastapi-server
    tty: true
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - mysql_network
    working_dir: /usr/src/app
    env_file:
      - .env

  react:
    build: ./frontend
    container_name: react-container
    hostname: react-server
    tty: true
    environment:
      - NODE_ENV=DEVELOPMENT
      - PORT=3000
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"

  mysql:
    build: ./database
    container_name: mysql-container
    hostname: mysql-server
    platform: linux/amd64 # for M2 Mac
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Japan
    ports:
      - 3306:3306
    networks:
      - mysql_network
    restart: always

  vector_db:
    image: qdrant/qdrant
    container_name: 'vector_db'
    ports:
      - "6333:6333"

volumes:
  mysql-data:
    name: mysql-data


networks:
  mysql_network:
    driver: bridge